# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907b323f83482ddaf890f3f549a093d3aa3db53dc72e7a47b9c52e7b1a7b926df3892f997cc45035cc67e0b3730ceda176341f235c80552673d6da5546ee111a

test:
  secret_key_base: 2905933df7a0126aae5fc5cb9c220d90efcbd8bb6ed2ac266af64c64a1827e71c5935e5c35b4fa982fd3fc99e0ef9d3c1a7349c0210b96291de735ee336a87c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
